@startuml

left to right direction
skinparam actorStyle awesome
title Cas d'utilisation - Gestion bancaire

actor Client
rectangle "Banque"{
    rectangle "Agence"{
    Client -- (Gére le compte client)
    Client -- (ouvrir un compte)
    Directeur -- (Gére l'agence)
    Employée -- (Conseil le client)
        }
}
@enduml
